AWSTemplateFormatVersion: 2010-09-09
Description: '3 Web-node with Load-balanced with First generation ELB '
Resources:
  vpc50c27e28:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 172.31.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: fc1ba308-f444-4119-b97b-94e2453a978b
  subnet10b1bf69:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 172.31.16.0/20
      AvailabilityZone: us-west-1b
      VpcId: !Ref vpc50c27e28
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d0476ebd-6ced-459e-b741-95a211c9db05
  subnet080a1252:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 172.31.0.0/20
      AvailabilityZone: us-west-1b
      VpcId: !Ref vpc50c27e28
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e0f3626d-f0aa-4062-bc41-119dea3e166d
  igw767b9d0f:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}
  dopt86ba0ffe:
    Type: 'AWS::EC2::DHCPOptions'
    Properties:
      DomainName: us-west-1.compute.internal
      DomainNameServers:
        - AmazonProvidedDNS
  acl79958101:
    Type: 'AWS::EC2::NetworkAcl'
    Properties:
      VpcId: !Ref vpc50c27e28
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 92cdb65f-74f1-4d91-aa53-245291fa14c5
  rtbe238a699:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref vpc50c27e28
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 19cd6a95-08c4-4036-bfd5-78092d2f20a3
  elbWebELB:
    Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
    Properties:
      Subnets:
        - !Ref subnet080a1252
        - !Ref subnet10b1bf69
        - subnet-57c3e81c
      HealthCheck:
        HealthyThreshold: '10'
        Interval: '10'
        Target: 'HTTP:80/heartbeat.html'
        Timeout: '2'
        UnhealthyThreshold: '2'
      ConnectionDrainingPolicy:
        Enabled: 'true'
        Timeout: '300'
      ConnectionSettings:
        IdleTimeout: '60'
      CrossZone: 'true'
      Instances:
        - !Ref instancei030f966de66e5ef56
        - !Ref instancei0631e772bd5d09af9
        - !Ref instancei072de2e61d14d296d
      SecurityGroups:
        - !Ref sgWebELB
      Listeners:
        - InstancePort: '80'
          LoadBalancerPort: '80'
          Protocol: HTTP
          InstanceProtocol: HTTP
      Tags:
        - Key: Name
          Value: ELBWebNode
  instancei0631e772bd5d09af9:
    Type: 'AWS::EC2::Instance'
    Properties:
      DisableApiTermination: 'false'
      InstanceInitiatedShutdownBehavior: stop
      ImageId: ami-082b5a644766e0e6f
      InstanceType: t2.micro
      KeyName: DevOps_1
      Monitoring: 'false'
      Tags:
        - Key: Name
          Value: WebNode2
      NetworkInterfaces:
        - DeleteOnTermination: 'true'
          DeviceIndex: 0
          PrivateIpAddresses:
            - PrivateIpAddress: 172.31.17.41
              Primary: 'true'
          GroupSet:
            - !Ref sgWebNode
          AssociatePublicIpAddress: 'false'
        - SubnetId: !Ref subnet10b1bf69
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e0bcd08e-616d-4745-bb66-2400cca40130
  instancei072de2e61d14d296d:
    Type: 'AWS::EC2::Instance'
    Properties:
      DisableApiTermination: 'false'
      InstanceInitiatedShutdownBehavior: stop
      ImageId: ami-082b5a644766e0e6f
      InstanceType: t2.micro
      KeyName: DevOps_1
      Monitoring: 'false'
      Tags:
        - Key: Name
          Value: WebNode3
      NetworkInterfaces:
        - DeleteOnTermination: 'true'
          Description: Primary network interface
          DeviceIndex: 0
          PrivateIpAddresses:
            - PrivateIpAddress: 172.31.7.123
              Primary: 'true'
          GroupSet:
            - !Ref sgWebNode
          AssociatePublicIpAddress: 'false'
        - SubnetId: !Ref subnet080a1252
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1710853e-1a9c-4d67-9e25-3cea53356a1e
  instancei030f966de66e5ef56:
    Type: 'AWS::EC2::Instance'
    Properties:
      DisableApiTermination: 'false'
      InstanceInitiatedShutdownBehavior: stop
      ImageId: ami-082b5a644766e0e6f
      InstanceType: t2.micro
      KeyName: DevOps_1
      Monitoring: 'false'
      Tags:
        - Key: Name
          Value: WebNode 1
      NetworkInterfaces:
        - DeleteOnTermination: 'true'
          DeviceIndex: 0
          PrivateIpAddresses:
            - PrivateIpAddress: 172.31.17.205
              Primary: 'true'
          GroupSet:
            - !Ref sgWebNode
          AssociatePublicIpAddress: 'false'
        - SubnetId: !Ref subnet10b1bf69
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8136ac3d-8bde-488c-9e00-e75f25254c3b
  sgWebNode:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: WebNode
      VpcId: !Ref vpc50c27e28
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 70638bc6-399a-4361-965c-3a4e31b3bd9b
  sgWebELB:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: WEBELB
      VpcId: !Ref vpc50c27e28
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3a96021f-9367-47b6-8593-ccc2a7afa411
  acl3:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: 'true'
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId: !Ref acl79958101
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7fba1481-88a0-49c5-9b38-554b6fb39b76
  acl4:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      CidrBlock: 0.0.0.0/0
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId: !Ref acl79958101
    Metadata:
      'AWS::CloudFormation::Designer':
        id: cacb5d5e-4571-43a9-9d8e-421e85686fef
  subnetacl5:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !Ref acl79958101
      SubnetId: subnet-57c3e81c
  subnetacl6:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !Ref acl79958101
      SubnetId: !Ref subnet10b1bf69
  subnetacl7:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !Ref acl79958101
      SubnetId: !Ref subnet080a1252
  gw2:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref vpc50c27e28
      InternetGatewayId: !Ref igw767b9d0f
  route2:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref rtbe238a699
    DependsOn: gw2
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 80140c28-7049-4bef-94b1-c75d6e53d801
  dchpassoc2:
    Type: 'AWS::EC2::VPCDHCPOptionsAssociation'
    Properties:
      VpcId: !Ref vpc50c27e28
      DhcpOptionsId: !Ref dopt86ba0ffe
  ingress3:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref sgWebNode
      IpProtocol: tcp
      FromPort: '80'
      ToPort: '80'
      CidrIp: 0.0.0.0/0
  ingress5:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref sgWebELB
      IpProtocol: tcp
      FromPort: '80'
      ToPort: '80'
      CidrIp: 0.0.0.0/0
  egress2:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      GroupId: !Ref sgWebNode
      IpProtocol: '-1'
      CidrIp: 0.0.0.0/0
  egress3:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      GroupId: !Ref sgWebELB
      IpProtocol: '-1'
      CidrIp: 0.0.0.0/0
Outputs:
  WebsiteURL:
    Description: URL for newly created LAMP stack
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - elbWebELB
          - DNSName
Metadata:
  'AWS::CloudFormation::Designer':
    fc1ba308-f444-4119-b97b-94e2453a978b:
      size:
        width: 870
        height: 780
      position:
        x: 90
        'y': 450
      z: 1
      embeds:
        - 3a96021f-9367-47b6-8593-ccc2a7afa411
        - 70638bc6-399a-4361-965c-3a4e31b3bd9b
        - 19cd6a95-08c4-4036-bfd5-78092d2f20a3
        - 92cdb65f-74f1-4d91-aa53-245291fa14c5
        - e0f3626d-f0aa-4062-bc41-119dea3e166d
        - d0476ebd-6ced-459e-b741-95a211c9db05
    3a96021f-9367-47b6-8593-ccc2a7afa411:
      size:
        width: 60
        height: 60
      position:
        x: 810
        'y': 510
      z: 2
      parent: fc1ba308-f444-4119-b97b-94e2453a978b
      embeds: []
      iscontainedinside:
        - fc1ba308-f444-4119-b97b-94e2453a978b
    70638bc6-399a-4361-965c-3a4e31b3bd9b:
      size:
        width: 60
        height: 60
      position:
        x: 810
        'y': 630
      z: 2
      parent: fc1ba308-f444-4119-b97b-94e2453a978b
      embeds: []
      iscontainedinside:
        - fc1ba308-f444-4119-b97b-94e2453a978b
    19cd6a95-08c4-4036-bfd5-78092d2f20a3:
      size:
        width: 240
        height: 240
      position:
        x: 510
        'y': 810
      z: 2
      parent: fc1ba308-f444-4119-b97b-94e2453a978b
      embeds:
        - 80140c28-7049-4bef-94b1-c75d6e53d801
      iscontainedinside:
        - fc1ba308-f444-4119-b97b-94e2453a978b
    80140c28-7049-4bef-94b1-c75d6e53d801:
      size:
        width: 60
        height: 60
      position:
        x: 540
        'y': 870
      z: 3
      parent: 19cd6a95-08c4-4036-bfd5-78092d2f20a3
      embeds: []
      isassociatedwith:
        - caa434d9-3050-4068-b314-e7a7d40e042d
      iscontainedinside:
        - 19cd6a95-08c4-4036-bfd5-78092d2f20a3
      dependson:
        - d46ca93c-75ac-4cf6-a351-b00056564fe7
    92cdb65f-74f1-4d91-aa53-245291fa14c5:
      size:
        width: 330
        height: 240
      position:
        x: 120
        'y': 810
      z: 2
      parent: fc1ba308-f444-4119-b97b-94e2453a978b
      embeds:
        - cacb5d5e-4571-43a9-9d8e-421e85686fef
        - 7fba1481-88a0-49c5-9b38-554b6fb39b76
      iscontainedinside:
        - fc1ba308-f444-4119-b97b-94e2453a978b
    cacb5d5e-4571-43a9-9d8e-421e85686fef:
      size:
        width: 60
        height: 60
      position:
        x: 150
        'y': 870
      z: 3
      parent: 92cdb65f-74f1-4d91-aa53-245291fa14c5
      embeds: []
      iscontainedinside:
        - 92cdb65f-74f1-4d91-aa53-245291fa14c5
    7fba1481-88a0-49c5-9b38-554b6fb39b76:
      size:
        width: 60
        height: 60
      position:
        x: 270
        'y': 870
      z: 3
      parent: 92cdb65f-74f1-4d91-aa53-245291fa14c5
      embeds: []
      iscontainedinside:
        - 92cdb65f-74f1-4d91-aa53-245291fa14c5
    e0f3626d-f0aa-4062-bc41-119dea3e166d:
      size:
        width: 240
        height: 240
      position:
        x: 510
        'y': 510
      z: 2
      parent: fc1ba308-f444-4119-b97b-94e2453a978b
      embeds:
        - 1710853e-1a9c-4d67-9e25-3cea53356a1e
      iscontainedinside:
        - fc1ba308-f444-4119-b97b-94e2453a978b
    1710853e-1a9c-4d67-9e25-3cea53356a1e:
      size:
        width: 60
        height: 60
      position:
        x: 540
        'y': 570
      z: 3
      parent: e0f3626d-f0aa-4062-bc41-119dea3e166d
      embeds: []
      iscontainedinside:
        - e0f3626d-f0aa-4062-bc41-119dea3e166d
    d0476ebd-6ced-459e-b741-95a211c9db05:
      size:
        width: 330
        height: 240
      position:
        x: 120
        'y': 510
      z: 2
      parent: fc1ba308-f444-4119-b97b-94e2453a978b
      embeds:
        - 8136ac3d-8bde-488c-9e00-e75f25254c3b
        - e0bcd08e-616d-4745-bb66-2400cca40130
      iscontainedinside:
        - fc1ba308-f444-4119-b97b-94e2453a978b
    8136ac3d-8bde-488c-9e00-e75f25254c3b:
      size:
        width: 60
        height: 60
      position:
        x: 150
        'y': 570
      z: 3
      parent: d0476ebd-6ced-459e-b741-95a211c9db05
      embeds: []
      iscontainedinside:
        - d0476ebd-6ced-459e-b741-95a211c9db05
    e0bcd08e-616d-4745-bb66-2400cca40130:
      size:
        width: 60
        height: 60
      position:
        x: 270
        'y': 570
      z: 3
      parent: d0476ebd-6ced-459e-b741-95a211c9db05
      embeds: []
      iscontainedinside:
        - d0476ebd-6ced-459e-b741-95a211c9db05
